server:
 port: 9092

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Root Password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  application:
   name: USER-SERVICE
  zipkin:
   base-url: http://localhost:9411/

resiliance4j.retry:
 instances:
  userService:
   maxRetryAttempts: 3
   waitDuration: 50000